@startuml Control Boundary
boundary RouteInput
boundary MapDisplay
boundary ListDisplay
boundary FilterDisplay
control RouteGenerator
control GetLocation
control GetNearbyInfo
control Notifications
control Login
control AdminOIFunctions
control AdminPhotoFunctions
control PhotoFunctions
control Filter
@enduml