@startuml Entity Class Diagram
OICollection *-- ObjectInterest
Photo --* ObjectInterest
User --* UserCollection
User <|-- Admin
User -- ObjectInterest
User -- Filters
InfoCollection *-- Information
@enduml