@startuml Sequence Diagram
actor User
control MapDisplay
control GetNearbyInfo
control GetLocation
entity OICollection
entity ObjectInterest
entity InfoCollection
entity Information
entity Filters

User -> MapDisplay: see map
activate MapDisplay
MapDisplay -> GetNearbyInfo: request OI+Info
activate GetNearbyInfo
alt select point
User -> MapDisplay: select point
MapDisplay -> GetNearbyInfo: give location
GetNearbyInfo -> GetNearbyInfo: location = selected point
activate GetNearbyInfo
GetNearbyInfo --> GetNearbyInfo
deactivate GetNearbyInfo
else use user's location
GetNearbyInfo -> GetLocation: request location
activate GetLocation
GetLocation --> GetNearbyInfo: userLocation
deactivate GetLocation
GetNearbyInfo -> GetNearbyInfo: location = userLocation
activate GetNearbyInfo
GetNearbyInfo --> GetNearbyInfo
deactivate GetNearbyInfo
end
GetNearbyInfo -> OICollection: location
activate OICollection
loop for all OI
	OICollection -> ObjectInterest: check within 5km
	activate ObjectInterest
	ObjectInterest --> OICollection
	deactivate ObjectInterest
end
OICollection --> GetNearbyInfo: OI list
deactivate OICollection
GetNearbyInfo -> InfoCollection: userLocation
activate InfoCollection
loop for all Information
	InfoCollection -> Information: check within 5km
	activate Information
	Information --> InfoCollection
	deactivate Information
end
InfoCollection --> GetNearbyInfo: Info list
deactivate InfoCollection
GetNearbyInfo -> Filters: Get Filters
activate Filters
Filters --> GetNearbyInfo: Filters
deactivate Filters
MapDisplay <-- GetNearbyInfo : OI+Info in Filters
deactivate GetNearbyInfo
MapDisplay --> User
deactivate MapDisplay
@enduml